# fly.toml app configuration file generated for churn-prediction-backend-silent-grass-5566 on 2025-05-09T11:37:52+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'churn-prediction-backend-silent-grass-5566'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
